// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/search/[hex].ts";
import * as $3 from "./routes/types.ts";
import * as $4 from "./routes/utils.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/search/[hex].ts": $2,
    "./routes/types.ts": $3,
    "./routes/utils.ts": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
